### ISSUE TITLE
Parameters don't get passed to constructor

### ISSUE THREAD

**Issue by noel-byT** [fluorumlabs/url-parameter-mapping#10]
Hey there,

first of all I'd really like to thank you for your extension. It's exactly the feature where I looked the first to see if there was such a thing in Vaadin. Thankfully by you, there is!

So, I'm a noob at Vaadin and I have a little question about a view component. I added the annotations like in your first example in your README.md and tried to render my component in the constructor simply by adding a setText() method with my parameter in it. Well, obviously the constructor is called first and then the parameters are being set. My question is: Which method do I use to render my component?

My first solution is to use a `AfterNavigationObserver` so I can access my parameters and render my text.

```@Route(value = "product")
@UrlParameterMapping(":productId")
public class ProductView extends Div implements HasUrlParameterMapping, AfterNavigationObserver {

	private Integer productId;

	@UrlParameter(name = "productId")
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public ProductView() {
		
	}

	@Override
	public void afterNavigation(AfterNavigationEvent afterNavigationEvent) {
		if(null != productId) {
			setText("Product ID: " + productId);
		} else {
			setText("No Product ID.");
		}
	}
}
````

How would you solve it?

Thank you very much!
Greetings from Germany.

**Comment by fluorumlabs** [comment]
Hi!

It is not possible to get parameters during construction due to fact that there is no location (path and/or query parameters available at the time of construction). In fact `HasUrlParameterMapping` extends `HasUrlParameter` interface, that is called by the router when it processes navigation events.

Usually we implement `BeforeEnterObserver` interface in our views and do all the heavy lifting in `void beforeEnter(BeforeEnterEvent beforeEnterEvent)` method. It has the benefit of being possible to redirect to another (if needed) with `beforeEnterEvent.rerouteTo(...)`.

Kind regards,
Artem

**Comment by noel-byT** [comment]
Thanks!
